" Specify a directory for plugins
" - For Neovim: ~/.local/share/nvim/plugged
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')
Plug 'kien/ctrlp.vim'
" Plug 'w0rp/ale'
Plug 'rafi/awesome-vim-colorschemes'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'leafgarland/typescript-vim'
Plug 'pangloss/vim-javascript'
Plug 'mxw/vim-jsx'
Plug 'bfrg/vim-cpp-modern'
Plug 'justinmk/vim-syntax-extra'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'sheerun/vim-polyglot'
Plug 'preservim/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'rhysd/vim-clang-format'
Plug 'majutsushi/tagbar'
Plug 'bling/vim-bufferline'
call plug#end()

colorscheme rdark-terminal2

set noexpandtab
set sw=4 ts=4
set updatetime=500
set number

let g:airline_powerline_fonts = 1

let g:gitgutter_sign_added = "│"
let g:gitgutter_sign_modified = "│"

" VIM Airline

if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif
" unicode symbols
let g:airline_left_sep = '»'
let g:airline_left_sep = '▶'
let g:airline_right_sep = '«'
let g:airline_right_sep = '◀'
let g:airline_symbols.linenr = '␊'
let g:airline_symbols.linenr = '␤'
let g:airline_symbols.linenr = '¶'
let g:airline_symbols.branch = '⎇'
let g:airline_symbols.paste = 'ρ'
let g:airline_symbols.paste = 'Þ'
let g:airline_symbols.paste = '∥'
let g:airline_symbols.whitespace = 'Ξ'

" airline symbols
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
let g:airline_symbols.branch = ''
let g:airline_symbols.readonly = ''
let g:airline_symbols.linenr = ''

let g:airline#extensions#coc#enabled = 1

" Highlight JSON comments
autocmd FileType json syntax match Comment +\/\/.\+$+

map <C-n> :NERDTreeToggle<CR>
nmap <C-\> :TagbarToggle<CR>

set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*.o
set tags=./tags;./.git/tags
